### ISSUE TITLE
`x` does not keep selecting lines

### ISSUE THREAD

**Issue by jameynakama** [chtenb/helix.vim#1]
Hey, I love that you've done this! I really like helix's movements, but the editor itself isn't really ready for prime-time, in my opinion, due to its lack of plugins and configurability.

One thing I've noticed right away is that `x` doesn't continue to select lines; it just toggles line selection if you keep pressing it.

**Comment by chtenb** [comment]
I pushed a fix that should mitigate this. I personally use the bindings from apocryphal.vim:

```
" More intuitive whole line selection using J/K
map J ZVv
xmap vJ Zjv
map K ZVv
xmap vK Zkv

noremap <A-j> J
```

which is inspired by this helix map: https://github.com/helix-editor/helix/pull/9080#issuecomment-2008964831

**Comment by jameynakama** [comment]
EXCELLENT, thank you! I tried but couldn't figure it out.
